# Generated by Django 4.2.6 on 2023-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_name', models.CharField(max_length=200)),
                ('maker', models.CharField(max_length=100)),
                ('cc', models.IntegerField()),
                ('yearofproduction', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('rate_per_Hr', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
                ('seating_capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('vechilecatagory', models.CharField(default='', max_length=50)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_name', models.CharField(max_length=200)),
                ('maker', models.CharField(max_length=100)),
                ('cc', models.IntegerField()),
                ('yearofproduction', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('rate_per_Hr', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
                ('seatingcapacity', models.IntegerField()),
                ('fueltype', models.CharField(max_length=20)),
                ('vechilecatagory', models.CharField(default='', max_length=50)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
            ],
        ),
    ]
